# Habilita el uso de las librerías modernas de AndroidX (Jetpack Compose, Room, Hilt, etc.)
android.useAndroidX=true

# Deshabilita la conversión automática de librerías viejas (no es necesaria en proyectos nuevos)
android.enableJetifier=false

# Optimiza la memoria de Gradle para que compile mucho más rápido
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Permite que las tareas de compilación se ejecuten en paralelo
org.gradle.parallel=true